### ISSUE TITLE
[Docs] Dead artoolkit links in main readme

### ISSUE THREAD

**Issue by valgaze** [jeromeetienne/AR.js#398] opened 2018-08-16 16:31 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**
Main readme contains links to artoolkit.org which now resolve to to an augmented reality firm which pur named [Daqri](http://www.daqri.com) which evidently purchased ARToolkit & re-released it in 2015

These links in main README under the [Full Featured Marker based
](https://github.com/jeromeetienne/AR.js#full-featured-marker-based) section redirect to the main Daqri landing page:

https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training

https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_barcode

https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_multi

**Please mention other relevant information such as the browser version, Operating System and Device Name**
N/A

**Comment by nicolocarpignoli** [comment] 2018-08-27 07:32
Yes, such links are dead by a long time. We have in plan to fix the readme

Duplicate of  https://github.com/jeromeetienne/AR.js/issues/362

**Closed by nicolocarpignoli** 2018-08-27 07:32 UTC
