### ISSUE TITLE
video and tracking seem slow on newer iOS devices

### ISSUE THREAD

**Issue by tbriley** [jeromeetienne/AR.js#460] opened 2019-01-29 07:44 UTC
could use a sanity check on this, but the video and tracking seem quite slow on certain newer model devices such as the iPhone XS.

tested on my own scenes and also https://stemkoski.github.io/AR-Examples/hello-cube.html

i did try lowering the source width and height as follows:

`   
this.arToolkitSource = new THREEx.ArToolkitSource({
      sourceType: 'webcam',
      sourceWidth: 640,
      sourceHeight: 480,
})
`

and lower values. while this seemed to resolve the issue on my next test. however subsequent tests showed the video and tracking again running slowly. in other words, results are inconsistent and sometimes it seems to run ok on these devices.

tested on an iPhone XS running iOS 12.1.2

**Comment by navanchauhan** [comment] 2019-02-12 12:20
Can't Confirm because I don't have a newer device, but iPhone 7+ runs on 60fps

**Comment by tbriley** [comment] 2019-02-12 12:37
@navanchauhan indeed, i believe we confirmed starting with the iPhone X.

**Comment by commentatorboy** [comment] 2019-02-22 11:16
Hm... I can not say for sure, but might be because of the browser?
Try different browsers.

**Comment by commentatorboy** [comment] 2019-06-28 22:54
Just revisited this. I can confirm that the problem is in Iphone X.
The problem is not happening in Iphone XS (only tested it on one).
A "solution" is to either, make the model smaller (MB size), or use the "VR" button. That worked for me. 
But not consistently. I also noticed that the Iphone is getting hot after a while.
So it might also be a CPU issue?
Also try and use a lower renderer as I described here:
https://github.com/jeromeetienne/AR.js/issues/494

**Comment by tbriley** [comment] 2019-06-29 00:13
@commentatorboy are you sure about this part?

> results are inconsistent and sometimes it seems to run ok on these devices

It's been some time since i tested this, but I'm quite sure i was able to reproduce this issue on an XS. One of the problems as I recall is that it was very intermittent -> sometimes it would happen 10 times in a row, sometimes I could load the scene 10 times and never see it.

**Comment by commentatorboy** [comment] 2019-06-29 08:18
The thing is that I tried to make it work alot.
The one I am testing with is working if the setup is very simple. Like if the 3D model is small (both size and dimensions) and only have one marker.
But as soon as I add more markers and the size is higher than 4 MB then I experience the issues.

Did the problem also occur when you tried to use the very basic setup? The one described in the README file?

**Comment by nicolocarpignoli** [comment] 2020-03-03 09:03
Closing this issue due to dismission of this repository. New repository of AR.js will be up at https://github.com/AR-js-org/AR.js/

Feel free to re-open the issue there if still valid.

**Closed by nicolocarpignoli** 2020-03-03 09:03 UTC
