### ISSUE TITLE
Documentation for how to use streaming video source type

### ISSUE THREAD

**Issue by JaeDukSeo** [jeromeetienne/AR.js#606] opened 2019-10-11 11:38 UTC
I don't want to use a direct image from my webcam but stream a video from another server.
Is this possible?

**Comment by nicolocarpignoli** [comment] 2019-10-12 10:05
duplicate of  https://github.com/jeromeetienne/AR.js/issues/571. Please wait for responses on the other thread about this same topic.

**Closed by nicolocarpignoli** 2019-10-12 10:05 UTC
Labels: documentation
