### ISSUE TITLE
Video source for marker tracking not working if cross-origin

### ISSUE THREAD

**Issue by germanviscuso** [jeromeetienne/AR.js#333] opened 2018-04-25 17:37 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using video as source of tracking there's a failure if the video is not hosted on the same domain

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's a sample Codepen:
https://codepen.io/germanviscuso/pen/WJbYzE
Here's a log from the debug console, it seems seems it's a cross-origin issue with the canvas:

Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at ARController._copyImageToHeap (https://rawgit.com/germanviscuso/AR.js/master/three.js/build/ar.min.js:25:30436)
    at ARController.detectMarker (https://rawgit.com/germanviscuso/AR.js/master/three.js/build/ar.min.js:25:25298)
    at ARController.process (https://rawgit.com/germanviscuso/AR.js/master/three.js/build/ar.min.js:25:19923)
    at ARjs.Context.THREEx.ArToolkitContext.ARjs.Context._updateArtoolkit (https://rawgit.com/germanviscuso/AR.js/master/three.js/build/ar.min.js:28:15367)
    at ARjs.Context.THREEx.ArToolkitContext.ARjs.Context.update (https://rawgit.com/germanviscuso/AR.js/master/three.js/build/ar.min.js:28:12083)
    at https://s.codepen.io/boomerang/iFrameKey-df63e233-2cd0-fb3b-66f6-dbe049d6aac3/index.html:100:20
    at https://s.codepen.io/boomerang/iFrameKey-df63e233-2cd0-fb3b-66f6-dbe049d6aac3/index.html:167:4
    at Array.forEach (<anonymous>)
    at animate (https://s.codepen.io/boomerang/iFrameKey-df63e233-2cd0-fb3b-66f6-dbe049d6aac3/index.html:166:16) 

**What is the expected behavior?**
An animated box on top of the Kanji marker seen in the video

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Latest Chrome on OSX

**Comment by nicolocarpignoli** [comment] 2018-08-02 13:28
duplicate of https://github.com/jeromeetienne/AR.js/issues/383

**Closed by nicolocarpignoli** 2018-08-02 13:28 UTC
