### ISSUE TITLE
Faulty marker position at high resolution

### ISSUE THREAD

**Issue by rremigius** [jeromeetienne/AR.js#449] opened 2018-12-12 14:11 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
In the AR.js three.js build, I am trying to process markers at larger distance, so I set the sourceWidth, sourceHeight (of the ArToolkitSource), canvasWidth and canvasHeight (of the ArToolkitContext) to 2560x1920. When trying this on my phone, from a distance of about 5 meters, it will track the marker correctly for a while. Moving closer, at some point the object on the marker will disappear, even though tracking was not lost. In fact, the object (or camera) has moved to a position with huge values (in the thousands) for x, y, and z and is therefore not visible on screen. Losing the marker for a moment and finding it again shows the object for a brief moment, but it can disappear quickly again, depending on the physical distance from the marker.

**If the current behavior is a bug, please provide the steps to reproduce.**
I adapted the basic three.js example and set the source and context dimensions to 2560x1920 there. Note that the image may be slightly distorted and the object off-center from the marker, but this is most likely related to aspect ratios not matching with the device (since the dimensions are hard-coded). The issue is not about these small tracking errors, but about the huge one described above.

Try here:
https://codepen.io/anon/pen/yGYYep
The camera position is logged in the console.

**What is the expected behavior?**
I would expect the tracked location not to jump to huge proportions and stay positioned on the marker in the video feed.
I tried the same with AR.js Aframe (raising source and canvas dimensions) as well as jsartoolkit5, and both seem to keep tracking the marker at the right location.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Using AR.js three.js build on Samsung Galaxy S8, Chrome 71.0.3578.83 on Android 8.0

**Comment by alexflom2** [comment] 2019-02-24 19:10
Hi @rremigius !
Struggling with the same thing...Did you manage to get it to work with high resolution?

**Comment by yomboprime** [comment] 2019-07-31 15:57
Hello, I have similar issue and I think I have a hint.

In my case it seems that the object matrices are distorted if the aspect ratio of the screen is not 4:3 (e.g, 1280x720). If the aspect is 4:3 I always get correct results (e.g. 640x480, 800x600)

The matrix skewing seems to be a ratio of the aspect difference.

BTW great ilbrary

**Comment by Shaninnik** [comment] 2019-08-14 03:39
I can confirm that with three.js build perspective becomes skewed if I set source width and height to anything other than 4:3 ratio (tried 1280x720)

**Comment by nicolocarpignoli** [comment] 2020-03-03 09:04
Closing this issue due to dismission of this repository. New repository of AR.js will be up at https://github.com/AR-js-org/AR.js/

Feel free to re-open the issue there if still valid.

**Closed by nicolocarpignoli** 2020-03-03 09:04 UTC
