### ISSUE TITLE
Start animation when the marker is detected, not before.

### ISSUE THREAD

**Issue by tocapixels** [jeromeetienne/AR.js#215] opened 2017-10-06 12:34 UTC
Hello,
I have loaded a GLTF animation and it works perfectly, the problem is that the animation starts automatically (hidden) when the page is loaded. Is it possible to start the animation only when the marker is detected?.
Is there any way to control it using the animation-mixer component for example?

Thanks!

url:[https://tocapixels.com/lab/ar/](url) 
Works with "Hiro" marker: [https://jeromeetienne.github.io/AR.js/data/images/HIRO.jpg](url)

Code:
```
<html>
	 <script src="https://aframe.io/releases/0.7.0/aframe.js"></script>
         <script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
<body style='margin : 0px; overflow: hidden;'>
  <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;' >
    <a-marker preset="hiro">
			 <a-entity
      id="drone"
      position="0 0 -1"
      scale="1 1 1" 
      gltf-model-next="src: url(https://tocapixels.com/lab/ar/models/busterDrone.gltf);"
animation-mixer="clip: BusterDrone; loop:once"
>
</a-entity>
    </a-marker>
	</a-scene>
</body>
</html>


```

**Comment by thehellrider** [comment] 2017-11-13 19:58
can you solve this??? I have the same issue

**Comment by lslzl3000** [comment] 2017-12-06 10:26
In the source code, there are events, such as:
```
arController.addEventListener('markerNum', function(ev) {
	console.log("Detected " + ev.data + " markers.")
});
arController.addEventListener('getMarker', function(ev) {
	console.log("Detected marker with ids:", ev.data.marker.id, ev.data.marker.idPatt, ev.data.marker.idMatrix);
	console.log("Marker data", ev.data.marker);
	console.log("Marker transform matrix:", [].join.call(ev.data.matrix, ', '));
});
arController.addEventListener('getMultiMarker', function(ev) {
	console.log("Detected multimarker with id:", ev.data.multiMarkerId);
});
arController.addEventListener('getMultiMarkerSub', function(ev) {
	console.log("Submarker for " + ev.data.multiMarkerId, ev.data.markerIndex, ev.data.marker);
});
```
You can do animation after 'getMarker', but these events are not implemented in current aframe version, you have to DIY the source code to fire those events.

**Comment by nicolocarpignoli** [comment] 2018-08-07 12:52
duplicate of https://github.com/jeromeetienne/AR.js/issues/217

**Closed by nicolocarpignoli** 2018-08-07 12:52 UTC
