### ISSUE TITLE
Vertical Squeez on all examples using Google Pixel

### ISSUE THREAD

**Issue by Samsy** [jeromeetienne/AR.js#60] opened 2017-05-09 15:54 UTC
I investigated a bit, but could not find a solution for this.
The video-feed got a squared format 480 x 480.
Looks well using landscape, but everything is squeezed using portrait mode.

**Comment by Samsy** [comment] 2017-05-15 12:45
Landscape behave nicely, portrait squeezes the whole thing.
I had a look but could not find where this thing happen
@jeromeetienne any ideas?

![GitHub Logo](http://i.imgur.com/c9YUUsB.jpg)

![GitHub Logo](http://i.imgur.com/fJ3Wzi8r.jpg)

**Comment by jeromeetienne** [comment] 2017-05-15 20:53
It is a known issue. Not specific to the pixel.

It is an bug in the aspects ratio handling.

The current "fix" is to load and use your apps in landscape... This is what
I do until I got time to fix this 😄

On May 15, 2017 1:45 PM, "Honigstein Samuel" <notifications@github.com>
wrote:

Landscape behave nicely, portrait squeezes the whole thing.
I had a look but could not find where this thing happen
@jeromeetienne <https://github.com/jeromeetienne> any ideas?

[image: GitHub Logo]
<https://camo.githubusercontent.com/dbfc8bb6383e96401c230ed4f828e44d689be7dc/687474703a2f2f692e696d6775722e636f6d2f633959555573422e6a7067>

[image: GitHub Logo]
<https://camo.githubusercontent.com/02a1fe84484d2d8f7aff69ff03f874193dca9179/687474703a2f2f692e696d6775722e636f6d2f664a33577a6938722e6a7067>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jeromeetienne/AR.js/issues/60#issuecomment-301463929>,
or mute the thread

**Comment by Samsy** [comment] 2017-05-16 15:19
Oh alright ! Can you point me where it is handled so I can have a proper look ? Is it in the artoolkitsource ?

**Comment by jeromeetienne** [comment] 2017-05-16 15:24
sure, here it is https://github.com/jeromeetienne/AR.js/blob/master/three.js/threex-artoolkitsource.js#L201

note that it is an ugly mess :) because i dunno how to actually resize, so i keep the original aspect and trick the css. 

I would love if you could fix the portrait/landscape issue and still to remain compatible with the jsartoolkit :)

**Comment by Samsy** [comment] 2017-05-17 11:07
A real quick fix, is to force the webRTC constrains to approach the ratio of the camera.dat file.

You can add :

   minAspectRatio: 1.33333333333

to the webrtc mandatory constrains to force not having a squared video feed.

**Comment by pikilipita** [comment] 2017-07-04 12:51
Any update on this issue?
Not sure where I should apply the proposed fix...

**Comment by patricknelson** [comment] 2017-07-20 03:29
Just chiming in to register my interest in a fix to this as well. I have a particular application where it'd be very useful to have the vertical space to move objects around that are superimposed over the AR marker. Right now landscape mode limits your vertical mobility and that's necessary in my particular use case about half the time.

**Comment by sonalranjit** [comment] 2017-09-08 03:53
@Samsy which camera.dat file are you talking about for the fix. If you are referencing the camera_param.dat its a binary file. where would i add the minAspectRatio?

**Comment by pqml** [comment] 2017-09-14 17:12
I had the same issue using ar.js three api & three.

One fix can be to update the camera projection matrix at each `orientationchange` event and invert the aspect ratio when the device is in landscape mode


```js

window.addEventListener('orientationchange', () => {
   // On non-orientable device, isLandscape is set to true
  const isLandscape = window.orientation !== undefined
    ? (window.orientation === -90 || window.orientation === 90)
    : true

  let matrix = artoolkitContext.getProjectionMatrix()
  if (isLandscape) {
    mat = mat.clone()
    const ratio = 4 / 3
    matrix[0] *= ratio
    matrix[5] *= 1 / ratio 
  } 
  camera.projectionMatrix.copy(matrix)
})
  artoolkitContext.init(() => {
    landscapeProjMatrix = arContext.getProjectionMatrix().clone()
    portraitProjMatrix = arContext.getProjectionMatrix().clone()
    const mult = arContext.parameters.canvasWidth / arContext.parameters.canvasHeight
    portraitProjMatrix.elements[0] *= mult
    portraitProjMatrix.elements[5] *= 1 / mult
    updateOrientation()
  })
```

**Comment by pikilipita** [comment] 2017-09-26 10:50
pqml, have you been able tu succesfully use your fix? I could not get it to work...

**Comment by pikilipita** [comment] 2017-10-04 09:29
I got a fix!
I was able to solve the aspect ratio issue and the wrong model rotation on portrait mode.
![xr_plus_pzt](https://user-images.githubusercontent.com/1799792/31168726-a020e1e8-a8f6-11e7-9b1f-96eafaa447c1.png)

Can you check this: url [https://xr.plus/pzt](url) ?
Is it ok on your phone?
If so, I will propose a commit.

**Comment by pqml** [comment] 2017-10-04 10:01
Yeah I figure out later that model rotation bug...

Your fix seems to work perfectly!

**Comment by RSpace** [comment] 2017-10-04 14:32
@pikilipita Tested a bit more:

* Safari on iOS11: Works
* Chrome on 61 on Android 7.0: Works
* Firefox 56 on Android 7.0: Pattern detected, no model appears

I use Firefox because I see better performance and fewer crashes than with Chrome for AR.js. However, most likely not related to your rotation fix.

Would love to see a PR for this asap, as I need portrait mode to work :)

Is this the fix?

```
ARjs.Source.prototype.copyElementSizeTo = function(otherElement){
  trace("copyElementSizeTo " + this.domElement.style.width + "x" + this.domElement.style.height);

//  console.log(otherElement );


  if (window.innerWidth > window.innerHeight)
  {
    //_log.html(window.innerWidth + "_" +window.innerHeight + " L " + this.domElement.style.width + "x" + this.domElement.style.height);
    //landscape
    otherElement.style.width = this.domElement.style.width
    otherElement.style.height = this.domElement.style.height
    otherElement.style.marginLeft = this.domElement.style.marginLeft
    otherElement.style.marginTop = this.domElement.style.marginTop
  }
  else {
    //_log.html(window.innerWidth + "_" +window.innerHeight + " P " + this.domElement.style.width + "x" + this.domElement.style.height);
    //portrait
    otherElement.style.height = this.domElement.style.height
    otherElement.style.width = (parseInt(otherElement.style.height) * 4/3)+"px";

    var ml = ((window.innerWidth- parseInt(otherElement.style.width))/2)+"px";//this.domElement.style.marginLeft
    otherElement.style.marginLeft = ml;
    otherElement.style.marginTop = 0;

  //  _log.html("W " + window.innerWidth + " x " +window.innerHeight + " O " + otherElement.style.width + "x" + otherElement.style.height + " ml " + ml + " V " + this.domElement.style.width + "x" + this.domElement.style.height);
  }

  ////c.arToolkitContext.arController.canvas.width = c.arToolkitContext.arController.canvas.height * 4 / 3;
}
```

**Comment by pikilipita** [comment] 2017-10-04 15:02
yes, but that's only part of it

**Comment by pikilipita** [comment] 2017-10-04 16:50
I've submitted a pull request from my fork, let's see if it get accepted

**Comment by RSpace** [comment] 2017-10-04 19:04
Fantastic. Already merged it into my own fork, works great. Thanks!

**Comment by Noko-Noko** [comment] 2017-10-11 11:15
@pikilipita thanks for this fix, it was pretty much a deal breaker for me, does your fork includes the custom markers fix too by any chance?
see https://github.com/jeromeetienne/AR.js/pull/168

**Comment by pikilipita** [comment] 2017-10-11 11:22
I am using custom markers, but they have the usual black frame around. 
I never had issue with markers, did not made changes on the code about markers

**Comment by Noko-Noko** [comment] 2017-10-12 09:53
@pikilipita Nope, tried with your fork and getting the same issue with custom markers, but I see you are not using the <a-marker type='pattern' patternUrl='path/to/pattern-marker.patt'> way but passing it directly on you js I guess, would be great to know how are you doing this.
Thanks

**Comment by rremigius** [comment] 2018-10-10 06:35
I see that @pikilipita 's fix was merged into the this master branch by now, but I am still experiencing the vertical stretch in portrait mode (Samsung S8). I see the issue is still open as well. Is there something else I can do to prevent the stretching? Even a hack would be fine for now (but preferably not forcing landscape mode).

**Comment by rremigius** [comment] 2018-10-10 20:20
Actually, [this fix](https://github.com/jeromeetienne/AR.js/issues/331#issuecomment-427992117) solved it for me!

**Comment by rremigius** [comment] 2018-10-10 20:45
I had the same problem but then it turned out I was using 1.5.0 for some reason. In the current build it seems to be fixed.

**Comment by YannKlein** [comment] 2018-11-15 01:54
Hi folks! 
I use the last version of three.min.js and ar.min.js in my code but I still experience the vertical squeeze problem.

I don't know whether it make sense or not but, I compared @pikilipita Oct 4th 2017 commit with my ar.js code,
I find the **three.js/src/threex/threex-artoolkitsource.js** fix in ar.js
But I don't find the **three.js/vendor/jsartoolkit5/js/artoolkit.api.js** one
(c.f. https://github.com/jeromeetienne/AR.js/commits?author=pikilipita&since=2017-10-01&until=2017-11-01 )

Did I miss something?

**Closed** 2018-12-21 11:17 UTC
