### ISSUE TITLE
Location-based AR Maximum Render Distance

### ISSUE THREAD

**Issue by richdunajewski** [jeromeetienne/AR.js#683] opened 2019-12-21 20:19 UTC
**Is your feature request related to a problem? Please describe.**
When placing large entities into a scene (like on the scale of a building), and place them for example 1 mile away from the camera, the entity doesn't render. Even though the object is large enough to be seen at that distance, it seems to not be rendered. If I move the object closer, it will render.

There is in fact a max render distance because the trick used to get a nearby object to not render if it's within the minDistance is to set the distance to the max integer value, sending it very far away.

**Describe the solution you'd like**
Assuming that this is an issue in AR.js and not deeper down, I'd like there to be an option for setting the maxDistance, similar to how we have the minDistance on the <a-camera> element.

**Describe alternatives you've considered**
I have tried to increase the scale of the object so it would definitely be visible to the camera, thinking it was just an issue of being too small to be seen. By moving the entity closer, I can get it to render.

**Additional context**
The reason that larger distances are required is to show buildings that are very tall and several miles away from the user. They will see a direction and distance to the building and a rough rendering of the building's shape. Think of a skyscraper that is visible 5 miles away. Due to the enormous size of the entity, it would definitely be visible at 5 miles. However, it appears there is a cutoff somewhere between 0.3 miles and 1.5 miles where nothing renders.

**Comment by nicolocarpignoli** [comment] 2019-12-22 09:49
Hi, it's a good feature to implement. I will look into this as soon as I have time.

**Comment by nicolocarpignoli** [comment] 2020-02-17 09:23
See: https://github.com/jeromeetienne/AR.js/pull/729 

I tried to use far="100000" (by default should be 10000, in meters, anyway) but does not seems to work for me: I still can see only objects under ~1km (1000 meters) of distance.

Ideas?

**Comment by nicolocarpignoli** [comment] 2020-02-17 09:24
With 'distance' and 'distanceMsg' properties now it's easy to see distance for each place you add: I can see some kind of 'schema' where places are not shown if distance > 1km (not precisely but it's a thing)

**Comment by nicolocarpignoli** [comment] 2020-02-17 09:37
Sorry, it seems to work! Step to reproduce:

- create basic only-html location based AR
- add this place:

` <a-box material="color: red;" scale="300 300 300" position="0 0 0" gps-entity-place="latitude: YOUR_LATITUDE; longitude: YOUR_LONGITUDE;"></a-box>`

on YOUR_LATITDE and YOUR_LONGITUDE add a place ~3km far from you.

- You should see it
- on camera component, add `far="1000"`
- you should not see it anymore, because now place is clipped under 1000 meters.

Let me know if it works for you too.

**Comment by nicolocarpignoli** [comment] 2020-02-17 10:44
Actually, using `a-frame-inspector ` (https://github.com/aframevr/aframe-inspector) I can see that ALL places are added correctly. 

<img src
![image](https://user-images.githubusercontent.com/22395670/74646787-c9b28000-517a-11ea-8bd0-18486bacb816.png)


I just can't understand why I cannot see some of them. It seems like a rendering problem, because if it is only one place, very far, It's showed, instead I found several problems when showing a lot of places, some of them distant.

I think, again, that it's not related to 'far' property (which works as expected) but rather a performance/rendering issue.

Have to investigate further.

**Comment by vinay-khare** [comment] 2020-03-02 13:10
> With 'distance' and 'distanceMsg' properties now it's easy to see distance for each place you add: I can see some kind of 'schema' where places are not shown if distance > 1km (not precisely but it's a thing)

Hi, could you help me as to how I can access distance and distanceMsg attributes?

**Comment by nicolocarpignoli** [comment] 2020-03-02 13:20
they are attributes of gps-entity-place entities (entity.getAttribute('distance'))

**Comment by nicolocarpignoli** [comment] 2020-03-02 13:21
and you can also get them on a listener for the `gps-entity-place-update-positon` event.

**Comment by vinay-khare** [comment] 2020-03-02 14:00
Thanks for the help!

**Comment by vinay-khare** [comment] 2020-03-02 14:06
Is there any other documentation apart from the Readme file in the aframe folder? Couldn't find gps-entity-place-update-positon in that, so was wondering if there's anything else.

**Comment by nicolocarpignoli** [comment] 2020-03-02 14:14
there will be in new AR.js repo. it's in wip: https://github.com/AR-js-org/AR.js/

**Comment by vinay-khare** [comment] 2020-03-03 06:19
Ok great. Thanks!

**Comment by nicolocarpignoli** [comment] 2020-03-04 20:31
added on new repo issues, we can continue there (see link on above comment).

**Closed by nicolocarpignoli** 2020-03-04 20:31 UTC
Labels: feature, location based
