### ISSUE TITLE
Hiro working great but custom markers not working

### ISSUE THREAD

**Issue by javismiles** [jeromeetienne/AR.js#216] opened 2017-10-06 20:39 UTC
Hi,
I'm trying all the examples of AR.js+Aframe, all works great with Hiro marker, but i can't manage to make them work with any custom marker, simple, not simple, detailed, not detailed, any kind, won't be recognized, Hiro works great, custom markers just don't work for me, what am I missing? I'm using the simple code available on your pages and loading custom markers with "a-marker type='pattern' patternUrl='jmarker.patt'" etc, 
thank you and congrats for this great project

**Comment by enesser** [comment] 2017-10-09 04:13
@javismiles Going to try this myself - but what format are the markers in? How do you create them?

**Comment by javismiles** [comment] 2017-10-09 09:54
hey enesser, thank you, its very simple:

a) I design the marker with Photoshop, following similar markers out there, making any changes i want
b) I then submit the generated .PNG file to an online app like this one:
https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html
c) which generates a .patt file which is what I then link to in the code

**Comment by javismiles** [comment] 2017-10-11 11:59
Thank you , I did those changes:

<script src="https://aframe.io/releases/0.5.0/aframe.min.js"></script>
<script src="https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
	<a-scene embedded artoolkit='sourceType: webcam;'>
    <a-marker preset='custom' url='jmarker.patt'>
      <a-box position='0 0.5 0' material='color: red;'></a-box>
    </a-marker>
    
	</a-scene>
</body>

however this is now generating this error:

A-Frame Version: 0.5.0 (Date 10-02-2017, Commit #110055d)
index.js:74 three Version: ^0.83.0
index.js:75 WebVR Polyfill Version: dmarcos/webvr-polyfill#a02a8089b
aframe-ar.js:8549 Uncaught TypeError: Cannot read property 'sceneEl' of undefined
    at r.init (aframe-ar.js:8549)

**Comment by javismiles** [comment] 2017-10-12 10:57
I finally made it work, it works now ;) 

however, just to let you know, on my Nexus 5X , the tracking using a simple basic box, is really not goody, can't follow it with precision, it's all over the place

**Comment by cypri1** [comment] 2017-10-12 11:28
@javismiles  how did you made it work? I have the same problem

**Comment by javismiles** [comment] 2017-10-12 13:15
hey Cypri, im  still not sure if the problem is the marker itself, but I made it work with a very simple marker i built and processed through https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html

and this is the code that works for me:

`<script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>
<script src="https://torch4ideas.com/ar/js/aframe-ar.js"></script>
<body style='margin : 0px; overflow: hidden;'>
  <a-scene embedded arjs='sourceType: webcam;'>
    
    <a-marker preset='custom' url='n2.patt'>
		<a-image src="myimg.jpg" position="0 0 0" rotation="90 180 0 ">
    </a-marker>
    
    <a-entity camera></a-entity>
  </a-scene>
</body>`

the only pity so far is that in my nexus 5x, the tracking speed is not good enough yet, when  I move the camera, the figure or image etc attached doesn't quite follow in real time, that's the only pity,

**Comment by cypri1** [comment] 2017-10-12 13:47
I tried but nothing appeared, the code I use is:

`<script src="https://aframe.io/releases/0.6.0/aframe.min.js"></script>
<script src="three.js/examples/vendor/three.js/examples/js/loaders/aframe-extras.loaders.min.js"></script>
<script src="https://torch4ideas.com/ar/js/aframe-ar.js"></script> `
<body style='margin : 0px; overflow: hidden;'>
  <a-scene embedded arjs='sourceType: webcam;'>
    <a-marker type='pattern' preset='custom' url='/path/to/pattern-marker.patt'>
      
      <a-entity scale="0.04 0.04 0.04" position="0 0 0"
      gltf-model-next="src: url(path/to/scene.gltf);"
      >
      </a-entity>
    </a-marker>
    <a-entity camera></a-entity>
  </a-scene>
</body>

**Comment by fofaria** [comment] 2017-10-16 01:19
hey @javismiles, i made the changes suggested on #164 and i've added your code snippet but still nothing :/. 
Does your marker follow any conventions or it's just and image you've uploaded to the generator?  

Thank you in advance.

**Comment by javismiles** [comment] 2017-10-16 10:36
hey friends, no conventions, i created it with photoshop, simple stuff, exported as png then uploaded to generator, it should work,
I'm a big fan of ar.js, this is wonderful work by Jerome, but still, and normal, quite a bit of chaos with documentation and also a-frame and ar.js many interconnection issues (like the issues with cursor), so it's early days, i wish i could help in any way, with documentation etc, this is wonderful work and we all support it, I hope it will become more and more stable, great job

**Comment by MWalid** [comment] 2017-10-24 21:57
Ah still doesn't work,
From the chrome inspector I see that pattern-marker.patt is not loaded at all,
No luck till now!
@javismiles

**Comment by javismiles** [comment] 2017-10-25 06:14
hey, for me it always works now MWalid, 
Im using `<a-marker preset='custom' url='n2.patt'>`
and a very simple marker, 
try to use the Hiro standard marker but as a custom marker to make sure, get a Hiro marker online, save it, upload it to Jerome tool, generate  the .patt file, then put it in the right folder, upload it,
and try with that, as a test

**Comment by WhiteRick** [comment] 2017-11-24 23:16
@javismiles  Can you post how you did your marker step by step?
I'm also trying with custom marker and it doesn't works, only Hiro marker works :(
I did an image with gip, nothing complicated just the word "ter" uploaded the image on https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html
Downloaded the .patt file and printed the image
On my html page y use your code 
<a-scene embedded arjs='sourceType: webcam;'>  <a-marker preset='custom' url='my-patt-file.patt'> <a-image src="myimg.jpg" position="0 0 0" rotation="90 180 0 "> </a-marker>  <a-entity camera></a-entity> </a-scene>

But it doesn't recognizes my marker it just recognizes hiro marker :(  any idea??

**Comment by kvanderd** [comment] 2017-11-24 23:38
Here are the steps.

1. Add to ar.js:

`else if( _this.data.preset === 'custom' ){
   arProfile.defaultMarkerParameters.type = 'pattern'
   arProfile.defaultMarkerParameters.patternUrl = _this.data.patternUrl;
   arProfile.defaultMarkerParameters.markersAreaEnabled = false`

2. Create your marker with a background color: 240, 240, 240
You can try this one - I am currently using this in one of my projects and it works: https://katharine.org/wp-content/uploads/2017/11/MASTER-marker-for-.patt-file-for-PYTHON.jpg

3. Add it to your code:
`<a-marker-camera preset='custom' type='pattern' url='assets/python.patt'></a-marker-camera>`

**Comment by WhiteRick** [comment] 2017-11-25 00:12
Hi @kvanderd !!

Thanks a lot by your reply I did the steps you wrote but it still doesn't works
I added the code to AR.js\aframe\buld\aframe-ar.js
My main directory where I compiled the library is AR.js, I have the http-server running 

The code in aframe-ar.js modified is:
                        // honor this.data.preset
			if( _this.data.preset === 'hiro' ){
				arProfile.defaultMarkerParameters.type = 'pattern'
				arProfile.defaultMarkerParameters.patternUrl = THREEx.ArToolkitContext.baseURL+'examples/marker-training/examples/pattern-files/pattern-hiro.patt'
				arProfile.defaultMarkerParameters.markersAreaEnabled = false
			}else if( _this.data.preset === 'kanji' ){
				arProfile.defaultMarkerParameters.type = 'pattern'
				arProfile.defaultMarkerParameters.patternUrl = THREEx.ArToolkitContext.baseURL+'examples/marker-training/examples/pattern-files/pattern-kanji.patt'
				arProfile.defaultMarkerParameters.markersAreaEnabled = false
			}else if( _this.data.preset === 'area' ){
				arProfile.defaultMarkerParameters.type = 'barcode'
				arProfile.defaultMarkerParameters.barcodeValue = 1001	
				arProfile.defaultMarkerParameters.markersAreaEnabled = true
			else if( _this.data.preset === 'custom' ){ 
				arProfile.defaultMarkerParameters.type = 'pattern' 
				arProfile.defaultMarkerParameters.patternUrl = _this.data.patternUrl;
				arProfile.defaultMarkerParameters.markersAreaEnabled = false
			}else {
				// console.assert( this.data.preset === '', 'illegal preset value '+this.data.preset)
			}

Then I downloaded your marker and uploaded to https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html

I downloaded the pdf, printed it, downloaded the .patt file and named it as your code in directory assets/python.patt

My html code is this:


<script src="vendor/aframe/build/aframe.min.js"></script>

<script src='../build/aframe-ar.js'></script>
<script>ARjs.Context.baseURL = '../../three.js/'</script>

<body style='margin : 0px; overflow: hidden;'>
		<a-scene embedded arjs='sourceType: webcam;'> 
			<a-marker-camera preset='custom' type='pattern' url='assets/python.patt'></a-marker-camera>
			</a-scene>
</body>

Any idea where the failure is?

PS: now the hiro marker doesn't works with these changes on my demo page

Best Regards
Ricardo

**Comment by kvanderd** [comment] 2017-11-25 00:28
@WhiteRick sounds like you followed the steps correctly. If you post a link to your repo I can take a look.

**Comment by WhiteRick** [comment] 2017-11-25 00:38
Thanks a lot by your reply @kvanderd  at this moment I don't have a repo, in fact I'm new with AR =) let me upload my code it and I'll send you the link

Best Regards
Ricardo

**Comment by WhiteRick** [comment] 2017-11-25 01:03
@kvanderd Thanks a lot by your time, I've found my mistake, when I copied the code to fix the library I erased a close bracket } on the else if sentence.

Now I've added it and the custom marker works =)

Best Regards
Ricardo

**Comment by kvanderd** [comment] 2017-11-25 01:08
@WhiteRick Great news. Glad I could help.

**Comment by cweise** [comment] 2017-12-01 14:08
Hi, I have also problems to get my marker running:

`<a-scene light="defaultLightsEnabled: true" embedded arjs>
    <a-assets>
          <a-asset-item id="santa" src="/assets/data/santa.gltf"></a-asset-item>
        </a-assets>
        <a-marker type="pattern" url="btc.patt">
          <a-entity animation-mixer gltf-model="#santa" rotation="-90 0 0" scale="0.3 0.3 0.3"></a-entity>
        </a-marker>
        <a-entity camera></a-entity>
      </a-scene>`

![bildschirmfoto 2017-12-01 um 15 06 05](https://user-images.githubusercontent.com/2069576/33486185-69c9a1c6-d6a9-11e7-8cf1-7409c0cba85b.png)

Do you have any ideas?

**Comment by ultradyran** [comment] 2018-01-20 19:00
Hi, i changed the code and it seemed only work with <a-marker-camera> but not <a-marker>, any fix?

**Comment by Vamoss** [comment] 2018-01-30 21:02
This is the solution:
https://github.com/jeromeetienne/AR.js/issues/216#issuecomment-346906569

**Comment by polyzer** [comment] 2018-02-16 15:04
Hello! I made as wrote in #216 , But it doesn't work. Anybody can provide an archive with working code? (aframe-ar).

**Comment by mattGraphics** [comment] 2018-03-06 15:17
The solution in https://github.com/jeromeetienne/AR.js/issues/216#issuecomment-346906569 isn't working for me either. Would love to know if there's a bug or if it's something i'm doing wrong.

**Comment by kvanderd** [comment] 2018-03-06 16:57
@mattGraphics @polyzer 

I wrote up a blog post about how to get this working - hopefully it will provide more context:
https://katharine.org/tutorials/custom-markers-ar-js/

**Comment by mattGraphics** [comment] 2018-03-07 08:22
Hi @kvanderd thanks for your message. 

As a result of your blog post I have found out where I was going wrong - the marker doesn't work for me unless it is stored somewhere on the web (in my case my github repository), not referenced locally on my computer. Once I had uploaded the marker to github and changed the 'url' accordingly it worked fine. Many thanks!

**Comment by Sevrex** [comment] 2018-03-17 10:13
@mattGraphics I'm still having issues with this even after putting my custom .patt file on a remote server, following https://katharine.org/tutorials/custom-markers-ar-js/ and trying different markers etc, could you please post a working code example? I've been trying to get this to work all day

**Comment by mattGraphics** [comment] 2018-03-19 09:13
Hi @Sevrex you can try my test site here: https://github.com/mattGraphics/mattGraphics.github.io
 this uses the custom marker: https://github.com/mattGraphics/mattGraphics.github.io/blob/master/assets/big-m.pdf

I noticed @jeromeetienne has made some changes to ar.js in the last few days, so the issues may have been resolved.

**Comment by tomtomtong** [comment] 2018-04-12 05:07
yes just change the reference script to the 1.5.5 version. Then all solve
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.5/aframe/build/aframe-ar.js"> </script>

**Comment by vettorazi** [comment] 2018-04-12 19:49
hey! i made work, deleting the camera-static tag and putting a-marker-camera tag in the bottom of the <a-scene> worked fine!
idk if this helps but i uploaded the .patt to my github (might help, idk)

here's the code if helps anyone:
    <a-scene embedded arjs ='trackingMethod: best;'>
    <a-anchor hit-testing-enabled='true'>
    <a-entity
      position="0 0.5 0"
      scale="0.005 0.005 0.005"
      gltf-model=”url(prebussola/scene.gltf);”>

      </a-entity>

    </a-anchor>
    <a-marker-camera preset='custom' type='pattern' url='https://raw.githubusercontent.com/vettorazi/aframe-gltf-models/master/marker.patt'>
</a-marker-camera>
    </a-scene>

**Comment by Sevrex** [comment] 2018-04-17 00:01
@mattGraphics finally got this working! Thanks to your example I was able to rule out code and found that it was the marker itself that was causing issues, cheers

**Comment by jhonyxf** [comment] 2018-04-27 01:46
@mattGraphics how do I display the gif by moving? 
or display video? in your example code did not work

**Comment by mattGraphics** [comment] 2018-04-27 08:25
Hi @jhonyxf When you say 'display the gif' do you mean display an animated gif? I haven't tried ar.js with an animated gif myself. I might try it myself later.

I just tested my .mov video example again ( https://mattgraphics.github.io/index-video.html ) and it worked fine. Make sure you're using the same pattern file: https://github.com/mattGraphics/mattGraphics.github.io/blob/master/assets/big-m.pdf

I wonder whether my video file may not work on some operating systems perhaps?

**Comment by jhonyxf** [comment] 2018-04-27 17:54
Hello @mattGraphics. I'm Brazilian, I'm sorry, my English. Yesterday when I tested the video it was displaying a blue screen in place of the video. I'm using android lollipop 5.1, thanks for the feedback

**Comment by mattGraphics** [comment] 2018-04-30 09:02
Hi @jhonyxf I'm not sure, I think it may be the video format I've used may not work on your Operating System? I'm not an expert - perhaps try the code with a video file you know works on your OS?

**Comment by jhonyxf** [comment] 2018-04-30 13:11
Hello @mattGraphics , thanks. I'm going to do a test with a video that runs on my smartphone and will return if it worked. Did you test with the gif?

**Comment by mattGraphics** [comment] 2018-04-30 14:25
Hi @jhonyxf Yes I did try it with an animated gif - it didn't work for me unfortunately.

**Comment by dlemm** [comment] 2018-06-24 14:45
Because I stumbled over where to put it in order to make it work I just would like to add just where to put the code from @kvanderd 
as she mentioned in her blog.post  search in the aframe/build/aframe-ar.js file for: 

```if( _this.data.preset === 'hiro' ){```

at the end of this if else put her code snippet:

```else if( _this.data.preset === 'custom' ){
   arProfile.defaultMarkerParameters.type = 'pattern'
   arProfile.defaultMarkerParameters.patternUrl = _this.data.patternUrl;
   arProfile.defaultMarkerParameters.markersAreaEnabled = false} ```

in your html file put 

```<a-marker preset='custom' type="pattern" url='path/to/your/pattern.patt'>```

then it should work. It does for me.

**Comment by nicolocarpignoli** [comment] 2018-07-03 13:35
can someone please make a PR for this?

**Comment by abhinav22rana** [comment] 2018-09-25 22:57
hey, i have made rotate globe demo on AR.js using hero marker, it is working fine... I wanted to add some touch event like zoom in zoom out on screen tab...can u tell any solution ??

**Comment by IgorDePaula** [comment] 2018-09-27 13:58
This not work for me too =/

**Comment by nicolocarpignoli** [comment] 2019-06-24 12:31
closing as now answer from author for a long time

**Comment by IgorDePaula** [comment] 2019-06-24 13:53
What? Anyone not answered me.

**Comment by nicolocarpignoli** [comment] 2019-06-24 14:07
Sorry, close that for mistake. I have done a clean to all stale issues. This one was not to be closed. Sorry again :)

**Comment by commentatorboy** [comment] 2019-06-28 22:30
@IgorDePaula What is the problem exactly?

**Comment by iggykov** [comment] 2019-07-08 21:52
I tried to follow all steps and comments in this thread and so far it is not working for me.
What am I doing wrong?

Below is my code and the custom marker is also attached.
![pattern-IK](https://user-images.githubusercontent.com/52668638/60845025-53f53780-a1db-11e9-9e55-0e1e5a5a52f4.png)

Basics:
I set the project-folder on my desktop. Inside the Index.html and the pattern_IK.ptt file.
I am opening my code in Firefox (found this to work best for Nicolo's Demo with yellow cube) and writing in SublimeText. 

```
<!doctype HTML>
<html>
<script src="https://aframe.io/releases/0.9.1/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.5/aframe/build/aframe-ar.js">

if( _this.data.preset === 'hiro' ){
else if( _this.data.preset === 'custom' ){
   arProfile.defaultMarkerParameters.type = 'pattern'
   arProfile.defaultMarkerParameters.patternUrl = _this.data.patternUrl;
   arProfile.defaultMarkerParameters.markersAreaEnabled = false} 

</script>

  <body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs='debugUIEnabled: false; sourceType=webcam;'>

		<a-marker preset="custom" type="pattern" patternUrl="/assets/pattern-IK.patt">
			<a-box position='0 0.5 0' material='color: yellow;' opacity='0.5'>
      		</a-box>
			</a-marker>

      	<a-marker-camera preset="custom" type="pattern" patternUrl="/assets/pattern-IK.patt">
      		</a-marker-camera>

      <a-entity camera></a-entity>
    </a-scene>
  </body>
</html>
```

**Comment by mattGraphics** [comment] 2019-07-09 07:32
@iggykov When I couldn't get it to work, I used an **external** url to the marker instead of it being **local** to the html file. So instead of it being:

```
<a-marker-camera preset="custom" type="pattern" patternUrl="/assets/my-patt.patt">
      		</a-marker-camera>
```

i changed it to:

`<a-marker-camera preset='custom' type='pattern' url='https://raw.githubusercontent.com/mattsGithub/randomfiles/master/my-patt.patt'></a-marker-camera>`
 
That resolved the problem for me - maybe give that a go?

https://github.com/jeromeetienne/AR.js/issues/216#issuecomment-371060214

**Comment by clubfrills** [comment] 2019-07-12 19:08
Is this deprecated? Having similar issues using custom markers. On desktop chrome, I'm getting "markersAreaEnabled :false" on my window. 

I've tried setting to a custom URL from within my Glitch.com assets with no luck. My .patt files are uploaded there.

**Comment by commentatorboy** [comment] 2019-07-18 19:59
@clubfrills Can you share the glitch? Or the code? Kind of hard to know why it is like that.

**Comment by clubfrills** [comment] 2019-07-20 14:46
This was solved, it was actually the same issue as an above commenter -- some of the AR marker examples on github and webpages are not the same color layout as the marker generator provided. The generator markers worked perfectly.


Matthew Pietrucha
Adjunct Professor of Music, Worcester Polytechnic Institute
IMGD Graduate Student



________________________________

**Comment by 1155077754** [comment] 2019-07-30 14:29
hello, I have the problem as title. I just use plain white marker but it is not working. But work perfectly for the "hiro" marker.
Here is my html code:
<script src="aframe0.7.1.min.js"></script>
<script src="aframe-ar.v2.js"></script> 
<script src="aframe-extras.loaders.min.js"></script>
<a-scene stat embedded arjs='trackingMethod: best; debugUIEnabled: false;
	'>
<a-marker preset='custom' type='pattern' url='pattern/pattern-demoPatt.patt'>
      <a-box position='0 0.5 0' material='color: green;'></a-box>
    </a-marker>
  <a-entity  camera>
  </a-entity>
</a-scene>

and I have modified the aframe-ar.js:
...
else if( _this.data.preset === 'area' ){
				arProfile.defaultMarkerParameters.type = 'barcode'
				arProfile.defaultMarkerParameters.barcodeValue = 1001	
				arProfile.defaultMarkerParameters.markersAreaEnabled = true
			}else if( _this.data.preset === 'custom' ){
				arProfile.defaultMarkerParameters.type = 'pattern'
				arProfile.defaultMarkerParameters.patternUrl = _this.data.patternUrl;
				arProfile.defaultMarkerParameters.markersAreaEnabled = false
			}
else ...

can you guys give me some help and give step by step instruction? Thank you very much.

P.S. my marker
![pattern-demoPatt](https://user-images.githubusercontent.com/31713893/62137630-d8d5fb80-b318-11e9-8ec7-57c24b8678c5.png)

**Comment by Beelzenef** [comment] 2019-09-11 12:04
hello there!

all good with 'Hiro' marker, but with custom marker... I'm facing some problems. I guess the marker is not recognised, nothing is showing

this is my code:

```html
<script src="https://aframe.io/releases/0.8.0/aframe.min.js">
    </script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.0/aframe/build/aframe-ar.js">
    </script>

<body style='margin: 0px; overflow: hidden;'>
    <a-scene embedded arjs='sourceType: webcam;'>
        <a-marker preset='custom' type='pattern' url='pattern.patt'>
            <a-entity obj-model="obj: url(model.obj); 
                                 mtl: url(model.mtl)">
            </a-entity>
        </a-marker>
        <a-entity camera></a-entity>
    </a-scene>
</body>
```

My marker is as simple as this [one](https://user-images.githubusercontent.com/6389665/64695477-87369a00-d49c-11e9-8563-2ddd7c084283.png).

All I get is `aframe-ar.js:4797 THREEx.ArMarkerControls: 'markersAreaEnabled' is not a property of this material.` message through browser console and `markersAreaEnabled:false` in the result page... what can I do? any ideas?

**Comment by nicolocarpignoli** [comment] 2019-09-11 12:10
if you put a simple <a-box> instead of <a-entity> it will show it?

**Comment by nicolocarpignoli** [comment] 2019-09-11 12:10
also use version 1.7.5 at least for ar.js and 0.9.0 for aframe

**Comment by Beelzenef** [comment] 2019-09-11 12:18
hello, @nicolocarpignoli, thanks for the quick answer! updated versions, using a simple box, same result

showing the code again just in case:

```html
<script src="https://aframe.io/releases/0.9.0/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.7.5/aframe/build/aframe-ar.js"></script>

<body style='margin: 0px; overflow: hidden;'>
    <a-scene embedded arjs='sourceType: webcam;'>
        <a-marker preset='custom' type='pattern' url='pattern.patt'>
            <!-- <a-entity obj-model="obj: url(model.obj); mtl: url(model.mtl)"></a-entity> -->
            <a-box position='0 0.5 0' material='color: yellow;'></a-box>
        </a-marker>

        <a-entity camera></a-entity>
    </a-scene>
</body>
```

**Comment by Beelzenef** [comment] 2019-09-11 13:45
I'm back!

I started reading again about markers... and it seems that my marker wasn't that simple as I thought... maybe the vertices of the 'w' letter? I don't know, but I tried with a simpler marker, just an 'I' letter, just horizonal and vertical lines, and that's it!

thanks for your time and help 😄

**Comment by commentatorboy** [comment] 2019-09-11 15:17
@Beelzenef I would recommend that you used a "pixelated" font, since that is more likely to work due to how .patt is setup.
https://github.com/jeromeetienne/AR.js/issues/437#issuecomment-446974868

**Comment by Beelzenef** [comment] 2019-09-11 15:20
I will try with pixelated font then, thanks a lot!

**Comment by droid001** [comment] 2019-09-12 07:42
Isn't it recommended to use a 16x16 grid? What I saw in .patt files is the matrix was of this size and one can speculate that detection would be best thereof.

**Comment by Beelzenef** [comment] 2019-09-14 12:36
Working with pixelated fonts and designs works fine, thanks for the advice, @commentatorboy! 🤘

**Comment by GregLMcDonald** [comment] 2019-12-04 20:21
I found that the marker training tool (https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html) sometimes downloaded a `.patt` file full of zeroes.  If your custom marker is not working, be sure to take a look in the `.patt` file and see whether the contents makes sense and reflect the pattern you want.

In my implementation, the Hiro marker preset was working correctly. To check whether it might be the`.patt` file that was the problem (rather than the syntax of my code), I fetched a copy of the Hiro pattern file (https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/marker-training/examples/pattern-files/pattern-hiro.patt) and used that as my "custom marker".  It worked great.  That's what prompted me to look inside these files.

I refreshed the marker training page, uploaded my image file again and downloaded the marker once again and this time there were not just a bunch of zeroes.  Hope that helps!

**Comment by kkaung** [comment] 2019-12-06 18:22
> I found that the marker training tool (https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html) sometimes downloaded a `.patt` file full of zeroes. If your custom marker is not working, be sure to take a look in the `.patt` file and see whether the contents makes sense and reflect the pattern you want.

How I got around the `.patt` file full of zeroes was to make the white parts slightly gray, put it through the training tool, and it generated a good `.patt` file.  I was able to use it on my marker which has the white background instead of gray.

Does anyone know if there's a lib for the training tool?  I need to be able to make custom patterns on the fly.

**Comment by nickvaras** [comment] 2020-02-05 15:10
Just to confirm the comment by kkaung, the custom markers not working is probably caused by a poorly chosen marker, and the `THREEx.ArMarkerControls: 'markersAreaEnabled' is not a property of this material.` message does not mean that the library is not working. In the contrary, a well chosen custom marker will work fine, even while displaying that message.

**Comment by JamesBotterill** [comment] 2020-02-16 14:11
It took me about 10 attempts to nail it and here's what I found.

1. Don't use dark background, grey worked best
2. Don't use transparent background, make sure it's solid.

**Comment by nicolocarpignoli** [comment] 2020-02-16 14:25
“10 tips to enhance your AR.js app.”  https://link.medium.com/OfHzdKvX73

**Closed** 2020-03-03 14:26 UTC

**Comment by GaryTimeless** [comment] 2020-04-04 20:11
> hey Cypri, im still not sure if the problem is the marker itself, but I made it work with a very simple marker i built and processed through https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html
> 
> and this is the code that works for me:
> 
> ` <a-scene embedded arjs='sourceType: webcam;'> <!-- handle marker with your own pattern --> <a-marker preset='custom' url='n2.patt'> <a-image src="myimg.jpg" position="0 0 0" rotation="90 180 0 "> </a-marker> <!-- add a simple camera --> <a-entity camera></a-entity> </a-scene>`
> 
> the only pity so far is that in my nexus 5x, the tracking speed is not good enough yet, when I move the camera, the figure or image etc attached doesn't quite follow in real time, that's the only pity,

is it possible to add multiple markers- so the camera can recognize two images/marker?

**Comment by PedroNan** [comment] 2020-09-30 01:05
Someone can fix error with custom markers??
I'm trying to get a custom marker work but still can't. I considered using a gray background and type = "pattern" preset = "custom" but still not work. I'm using Glitch to host the code online. I would appreciate some help! thanks.

**Comment by ReshiWiz** [comment] 2022-04-20 13:12
> * <a-marker-camera preset='custom' url='your-marker.patt'>...</a-marker-camera>

in url what to mention ..? path is not showing

**Comment by M4RC0N3** [comment] 2023-09-01 02:32
> yes just change the reference script to the 1.5.5 version. Then all solve
> 
> <script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.5/aframe/build/aframe-ar.js"> </script>

This work for me. Thanks man!!!! You are my hero
