### ISSUE TITLE
Back Camera on mobile - SOLVED!

### ISSUE THREAD

**Issue by curtello** [jeromeetienne/AR.js#86] opened 2017-06-01 12:37 UTC
I think I have a solution to the camera preference when using mobile.

The `navigator.getUserMedia` function is deprecated and you should instead use the newer `MediaDevices.getUserMedia` function. The [link](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) for the docs. 

in your [Threex.ArToolkitSource.js file](https://github.com/jeromeetienne/AR.js/blob/master/three.js/threex-artoolkitsource.js) at line 143 should then be changed to

```
var constraints = { video: { 
                   facingMode: "environment"  
                   mandatory: {
                                        maxWidth: _this.parameters.sourceWidth,
		                       maxHeight: _this.parameters.sourceHeight
		    		}
};
```

And if someone wants to instead use the 'selfie' camera they change "environment" to "user". You can even make a button to choose between the two.

However this might result in you changing a lot of code possibly

**Comment by jeromeetienne** [comment] 2017-06-03 18:38
ahhhh! great. i had some kludge there. i will incorporate that asap. 

how does it work if i have only user facing camera ? e.g. on a laptop with the internal camera

**Comment by jeromeetienne** [comment] 2017-06-03 18:39
see #74

**Comment by curtello** [comment] 2017-06-03 18:49
if statements maybe, hehe 😂 . Since AR.js is primarily for bringing AR on the phone, it only makes sense to have this feature instead. Every phone has a back camera. So actually for laptops, that is only necessary during development so the developer can just manually configure that part out

**Comment by jeromeetienne** [comment] 2017-06-04 10:08
i cant get it to work here. im likely missing something

@curtello do you mind doing a pull request ?

**Comment by curtello** [comment] 2017-06-04 12:44
I'll get on it

**Comment by MrRaam** [comment] 2017-06-04 13:35
Adding to this, we can also pull out the camera devices from mobile and give the user an option to choose either front or back camera when the screen opens. I have tried this earlier and it works like magic.

**Comment by curtello** [comment] 2017-06-04 13:37
what do you mean by pull out?

**Comment by MrRaam** [comment] 2017-06-04 14:21
` function init() {
  var videoSelect = document.querySelector('select#videoSource');
  var selectors = [videoSelect];

  function gotDevices(deviceInfos) {
   // Handles being called several times to update labels. Preserve values.
    var values = selectors.map(function(select) {
    return select.value;

   });
   selectors.forEach(function(select) {
    while (select.firstChild) {
     select.removeChild(select.firstChild);
    }
   });

> Pull all the available cameras from the device ( PC , Tab , Laptop or mobiles )

   for (var i = 0; i !== deviceInfos.length; ++i) {
    var deviceInfo = deviceInfos[i];
    var option = document.createElement('option');
    option.value = deviceInfo.deviceId;
    if (deviceInfo.kind === 'videoinput') {
     option.text = deviceInfo.label || 'camera ' + (videoSelect.length + 1);
     videoSelect.appendChild(option);

    } else {
     console.log('Some other kind of source/device: ', deviceInfo);
    }
   }
   selectors.forEach(function(select, selectorIndex) {
    if (Array.prototype.slice.call(select.childNodes).some(function(n) {
      return n.value === values[selectorIndex];
     })) {
     select.value = values[selectorIndex];
    }
   });
  }

  navigator.mediaDevices.enumerateDevices().then(gotDevices).catch(handleError);


  function gotStream(stream) {
   window.stream = stream; // make stream available to console
   video.srcObject = stream;
   // Refresh button list in case labels have become available
   return navigator.mediaDevices.enumerateDevices();
  }

  function start() {
   if (window.stream) {
    window.stream.getTracks().forEach(function(track) {
     track.stop();
    });
   }

   var videoSource = videoSelect.value;
   var constraints = {
    video: {
     deviceId: videoSource ? {
      exact: videoSource
     } : undefined
    }
   };
   navigator.mediaDevices.getUserMedia(constraints).
   then(gotStream).then(gotDevices).catch(handleError);
  }

 video
![choosecam](https://cloud.githubusercontent.com/assets/29176724/26762394/ff7c3b58-495e-11e7-9cb5-be6cffa35ca7.jpg)
Select.onchange = start;

  start();`

**Comment by curtello** [comment] 2017-06-04 14:29
Awesome stuff man. I get you now. Will integrate it

**Comment by MrRaam** [comment] 2017-06-04 14:37
Thanks @curtello ,  It should work, It's working for my application. However, thinking from the end user perspective we can keep the back camera as default. 

Note: if we use the above code there is no need for polyfill I believe.

**Comment by curtello** [comment] 2017-06-04 14:41
Just like I had said, the choice of camera wouldn't exactly make sense because ~99% of people will just want to use the back camera constantly so maybe only when building the project will the choosing of camera become necessary. Now the equivalent of this code in the `AFrame` implementation is what can bring problems, should the camera in use be the selfie camera.

**Comment by curtello** [comment] 2017-06-04 14:43
May I ask what you used to implement your app.

**Comment by MrRaam** [comment] 2017-06-04 15:02
Yes sometimes it depends upon the concept, some concept needs front cam and some don't. I used threejs and a bit of babylon initially to test out few things.

**Comment by curtello** [comment] 2017-06-04 15:03
and what web framework?
or at least can I see your repository for the example

**Comment by MrRaam** [comment] 2017-06-04 15:12
Sure, I like your curiosity. Web frameworks being a bit of jquery, larval and others.. Let's keep this thread for this issue. Ping me out for other quiries.

**Comment by curtello** [comment] 2017-06-04 15:15
i wanted to use Express but wanted to know how other people went about the whole issue of making a whole web app out of it. Isn't pinging you being intrusive 😂 . are you on gitter?
I don't see why this conversation needs to be publicized

**Comment by MrRaam** [comment] 2017-06-04 15:28
I wouldn't mind :) , yep gitter. can i see a working link of this demo in Ar.js? 
[](https://www.youtube.com/watch?v=EuF-k0ajsjk)

**Comment by curtello** [comment] 2017-06-04 15:32
it's not yet done so i wanted to see other people's implementations

**Comment by curtello** [comment] 2017-06-05 15:37
@MrRaam could I get your email so I can contact you

**Comment by MrRaam** [comment] 2017-06-05 16:33
Sure, meetanandram@gmail.com

**Comment by francesco-marafini** [comment] 2017-06-05 18:44
@curtello @jeromeetienne getUserMedia can be very uncooperative with deviceId constraint, especially on chrome for android.
In our PWA we resorted to "explore" various width and height combinations to get the maximum supported values on the user's device and then use the device ID from enumerateDevices with those values to get the back camera.
Works as a charm.
Only caveat is adapter.js for the shims.
If you want I can craft a pr

**Comment by jeromeetienne** [comment] 2017-06-11 13:58
i merged all the modification. So it is supposed to work now and it is using the new API.

It has been reported to work on IOS. and work on my chrome/firefox desktop. plus my android phone.

Lets close and reopen if we experiences issues :)

**Closed by jeromeetienne** 2017-06-11 13:58 UTC

**Comment by MrRaam** [comment] 2017-06-11 14:16
@Jerome Can we use it for one of our commercial project ?
ᐧ

**Comment by junzhaok** [comment] 2017-07-02 10:20
@MrRaam    Could you give me a demo of 86#  THX

**Comment by junzhaok** [comment] 2017-07-02 10:24
@MrRaam    
    the  demo of  you writed

![_20170702182148](https://user-images.githubusercontent.com/29834096/27769037-b2e8cc4c-5f53-11e7-96ba-2feca8a3474b.png)

**Comment by 254773230** [comment] 2017-07-02 15:12
I open the test link used  “wechat”，only front camera work，can not change to the back camera! 
Just instead use the newer MediaDevices.getUserMedia function and changed Threex.ArToolkitSource.js at line 143 in my file.
Any help?
Thanks

**Comment by MrRaam** [comment] 2017-07-03 02:46
@junzhoak the project code is bit huge, I'll condense and send it over to
you. Shortly.

**Comment by shadowfax6894** [comment] 2017-08-10 20:47
I'm not seeing how you can pass in a desired video source as an argument to the ArToolkitSource constructor. I see that you can hardcode it by changing the `facingMode` property from  "environment" to "user" within `userMediaConstraints`. However, it would be nice to pass in a camera's unique deviceId as a parameter of ArToolkitSource, that way users on a desktop can choose their desired video source if they have more than 1 camera (for example, surface books have the rear and front facing cameras). 

I see above that someone has designed an application to toggle back and forth between the front and back cameras, but I'm not seeing how to do this without making changes to the library itself.

So:
1. Is there already a way to do what I'm describing?
2. If not, would this be something people find useful? If people would like this feature, I can open a pull request to work on this.

Thanks!

**Comment by OmranAbazid** [comment] 2017-10-30 08:25
Here is a working solution of @MrRaam:
just add to your code or modify the  basic.html example
HTML:  
```
<div class="select">
      <label for="videoSource">Select Camera: </label><select id="videoSource"></select>
</div>
```
Code:
```
var videoSelect = document.querySelector("select#videoSource");
var selectors = [videoSelect];

function gotDevices(deviceInfos) {
  // Handles being called several times to update labels. Preserve values.
  var values = selectors.map(function(select) {
    return select.value;
  });
  selectors.forEach(function(select) {
    while (select.firstChild) {
      select.removeChild(select.firstChild);
    }
  });

  for (var i = 0; i !== deviceInfos.length; ++i) {
    var deviceInfo = deviceInfos[i];
    var option = document.createElement("option");
    option.value = deviceInfo.deviceId;

    if (deviceInfo.kind === "videoinput") {
      option.text = deviceInfo.label || "camera " + (videoSelect.length + 1);
      videoSelect.appendChild(option);
    } else {
      console.log("Some other kind of source/device: ", deviceInfo);
    }

    selectors.forEach(function(select, selectorIndex) {
      if (
        Array.prototype.slice.call(select.childNodes).some(function(n) {
          return n.value === values[selectorIndex];
        })
      ) {
        select.value = values[selectorIndex];
      }
    });
  }
}

navigator.mediaDevices
  .enumerateDevices()
  .then(gotDevices)
  .catch(handleError);

function gotStream(stream) {
  arToolkitSource.domElement.srcObject = stream; // make stream available to console
  // video.srcObject = stream;
  // Refresh button list in case labels have become available
  return navigator.mediaDevices.enumerateDevices();
}

function start() {
  if (window.stream) {
    window.stream.getTracks().forEach(function(track) {
      track.stop();
    });
  }
  var videoSource = videoSelect.value;
  var constraints = {
    video: {
      deviceId: videoSource ? { exact: videoSource } : undefined
    }
  };
  navigator.mediaDevices
    .getUserMedia(constraints)
    .then(gotStream)
    .then(gotDevices)
    .catch(handleError);
}

videoSelect.onchange = start;

function handleError(error) {
  console.log("navigator.getUserMedia error: ", error);
}

start();

```
if you see above I just used: 
arToolkitSource.domElement.srcObject = stream; 
to the switch the artoolkit camera stream source to the new source.

**Comment by rustynymph** [comment] 2017-10-30 16:10
@OmranAbazid This is fantastic and so simple, thank you!

**Comment by MrRaam** [comment] 2017-10-31 02:46
I'm glad that my work is helping out you guys a lot. Cheers keep coding.

**Comment by javismiles** [comment] 2017-11-28 15:34
Good day friends, 
I am trying to use the code from @OmranAbazid  , it recognizes the 2 cameras of the phone and all good, but when changing cams, it doesn't switch between them, I see also this error:

`navigator.getUserMedia error:  ReferenceError: arToolkitSource is not defined
    at gotStream (arzxdsfdsf:187)
    at <anonymous>"

any tips? thanks a lot :)
`

**Comment by javismiles** [comment] 2017-11-28 16:42
ok I made  it work, I just don't know if this is the ideal way, please let me know ;)
I went inside of aframe-ar.js,

and I added this call here:

`	// attach
        this.domElement = domElement
        this.domElement.style.position = 'absolute'
        this.domElement.style.top = '0px'
        this.domElement.style.left = '0px'
        this.domElement.style.zIndex = '-2';
	
	this._mynewcode();`


And then  in that function I added your code

`ARjs.Source.prototype._mynewcode = function(){
	var _this = this
	var parent = this;
	
var videoSelect = document.querySelector("select#videoSource");
var selectors = [videoSelect];

function gotDevices(deviceInfos) {
  // Handles being called several times to update labels. Preserve values.
  var values = selectors.map(function(select) {
    return select.value;

etc, etc
`
and then in gotstream I do

`function gotStream(stream) {
  parent.domElement.srcObject = stream; // make stream available to console
  return navigator.mediaDevices.enumerateDevices();
}
`
and it all works great,
but maybe there is a better place to put all this?
let me know if there is

thanks very much for all your support ;)

**Comment by javismiles** [comment] 2017-11-28 18:23
so I got how to take it out of aframe-ar
setting in aframe-ar:

`var domElement = document.createElement('video');
domElement.setAttribute('id', 'camvid');`

and then outside of aframe-ar:

`  function gotStream(stream) {
	document.getElementById("camvid").srcObject	= stream;   
    return navigator.mediaDevices.enumerateDevices();
  }`

now I will see why once in a while the switch fails, but i think it has to do
with speed of change and the device

**Comment by javismiles** [comment] 2017-11-28 22:09
So I got the console error, whenever the switch fails, it is:

Uncaught (in promise)
DOMException: the play() request was
interrupted by a new load request
gotStream function
promise (async)


any idea how to prevent this from happening, or maybe its unavoidable because of the speed and memory limits of my nexus 5X phone?
it never happens at the start, it begins happening after a few switches

**Comment by Disorrder** [comment] 2018-12-05 16:47
I've got a problem with back camera. Well, I've used code described above with `enumerateDevices` and `getUserMedia` methods, got stream object of back camera with `deviceId` property, tried to set to video DOM and got such error: `NotReadableError: Could not start video source`. Front camera works good, but when I'm swithing to back, getting such error. Permissions was accepted. This problem is only on Android devices, iPhone switches on back camera automatically.

Also, I'm getting this trouble here: https://simpl.info/getusermedia/sources/
When I'm switching to another camera

**Comment by Darrel-Collinsworth** [comment] 2019-11-07 04:54
Has anyone solved the problem for android? I'm having a problem where ar.js is defaulting to my wide angle lens and it isn't letting me switch when I click the drop down.

**Comment by ybinstock** [comment] 2019-11-21 16:31
I'm having the same issue as well.

**Comment by Darrel-Collinsworth** [comment] 2019-11-22 00:55
I found someone who said they made some code to get it to switch. but when i tried using it it wouldn't let me switch the cameras around. The best option is using firefox because it explicitly asks which camera would you like to use. I don't really like that option since I'd really like the experience to work on any browser.

Does anyone know of any alternatives to Ar.js in general? I still love AR.JS but I do worry about it's stability in the future.

**Comment by nicolocarpignoli** [comment] 2019-11-24 22:11
I will try to include this feature on next version

**Comment by nicolocarpignoli** [comment] 2019-11-29 13:18
I may have done some progress to this. Can anyone please test? See there: https://github.com/jeromeetienne/AR.js/pull/661#issuecomment-559787020
