### ISSUE TITLE
Show object without a marker?

### ISSUE THREAD

**Issue by luckylast** [jeromeetienne/AR.js#502] opened 2019-04-10 00:56 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I'm looking for a way to take photo with AR object without marker on web browser. Is it possible ?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I hope when the time i open web camera, the ar object already inside. 
Thanks. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**Comment by nicolocarpignoli** [comment] 2019-04-10 09:26
Currentlly, no.
Also, this is duplicate of https://github.com/jeromeetienne/AR.js/issues/190

**Closed by nicolocarpignoli** 2019-04-10 09:26 UTC
