### ISSUE TITLE
redundant code in all the builds

### ISSUE THREAD

**Issue by paztis** [jeromeetienne/AR.js#257] opened 2017-11-20 22:10 UTC
In all the build processes, there's the inclusion of the 2 libs:

three.js/vendor/jsartoolkit5/build/artoolkit.min.js
three.js/vendor/jsartoolkit5/js/artoolkit.api.js

but artoolkit.api.js is already included and minified inside artoolkit.min.js
So all the function are declared a second time and override the first ones.

cf [https://github.com/artoolkit/jsartoolkit5#artoolkit-js-debug-build](url) and [https://github.com/artoolkit/jsartoolkit5#artoolkit-js-debug-build](url)

**Comment by ZoltanVeres** [comment] 2017-11-24 10:15
Duplicate of @ #36 Please follow progress there. Suggestions and PRs are very welcome. Thanks for your effort!

**Closed by ZoltanVeres** 2017-11-24 10:15 UTC
Labels: duplicate
