### ISSUE TITLE
The model material is flashing all the time 

### ISSUE THREAD

**Issue by 544531645** [jeromeetienne/AR.js#430] opened 2018-10-31 10:37 UTC
![image](https://user-images.githubusercontent.com/15622364/47782773-fd765600-dd3b-11e8-8126-89ca6df4fe79.png)
![image](https://user-images.githubusercontent.com/15622364/47782783-02d3a080-dd3c-11e8-94d9-fdb3290fad1d.png)
![image](https://user-images.githubusercontent.com/15622364/47782793-06ffbe00-dd3c-11e8-9265-5d42a69287e2.png)
It seems that FPS is very high and flickering all the time. Is there any solution?

**Comment by 544531645** [comment] 2018-11-01 08:40
@droid001

**Comment by droid001** [comment] 2018-11-01 13:18
@544531645 Don't knwo why you pinged med but anyhow, I have the same problem with one of my models. Don't know the solution to this though.

**Comment by droid001** [comment] 2018-11-02 05:45
Seems like this is a duplicate of #401 . Seems like the renderer can be replaced with a custom three.js one.

**Comment by 544531645** [comment] 2018-11-02 06:08
@droid001   no, I change render,but no use

**Comment by darkscarletorchid** [comment] 2018-11-02 14:28
Having the same issue with rendering obj models with mtl materials though before everything worked fine with the same settings. replacing renderer didn't help either

**Comment by vettorazi** [comment] 2019-01-23 17:25
same here...

**Comment by breezeLoganGithub** [comment] 2019-03-28 06:14
same here....
my code at 
https://github.com/breezeLoganGithub/arwrong

notes:
change the index.html
var app = new APP();
to
var app = new PureApp();

fbxAnimation.loadObject('module/nv01.fbx',null,0.04);
to
fbxAnimation.loadObject('module/nv01.fbx',null,1);
can see the origin fbx module,it ok.but use track it's would lost some cloth.

![error](https://user-images.githubusercontent.com/19275567/55134442-c168e500-5163-11e9-96ce-9b476ac11869.jpg)

**Comment by breezeLoganGithub** [comment] 2019-03-29 10:33
Is it posible to optimizate the smooth control to eliminate the flashing？

**Comment by MrRaam** [comment] 2019-04-14 06:29
I had exactly the same issue. After a few trial and errors, I was able to fix it

1. Add recent version of aframe

2. Add `<a-scene embedded artoolkit='sourceType: webcam;' renderer='logarithmicDepthBuffer: true;'>`

3. Add `<a-marker-camera camera="far:100000; near:0.01" >`

4. - Main reason was the light, Remove all lights and add only the hemisphere light into the scene and improvise upon other lights later on.

Hope this would resolve your issue too.

**Comment by commentatorboy** [comment] 2019-06-28 22:56
Also this might help too:
https://github.com/jeromeetienne/AR.js/issues/494

**Comment by 544531645** [comment] 2019-07-03 09:06
#455 I fixed it

**Closed** 2020-02-07 09:54 UTC
