### ISSUE TITLE
Change Webcam stream

### ISSUE THREAD

**Issue by MichaelVonB** [jeromeetienne/AR.js#612] opened 2019-10-15 11:22 UTC
**Describe the bug**
I made an AR App, where I also use a QR-Code Scanner. Once the QR-Code Scanner detecs a QR-Code, I will add an a-marker to the scenen with an element on it. 
The Problem that I am having is that i needed two streams for the process. I wasnt able to use the arjs stream for the QR-Code Scanner neither was I able to use the getusermedia stream I created for the QR-Scanner in ar.js. Is there any way to use a different stream?

**Expected behavior**
I want to tell ar.js to use the stream I created in a video tag 
`<video` `#videoElement></video>`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Firefox

**Smartphone (please complete the following information):**
 - Device: Huawei P20, Sony Xperia Z5, Galaxy Tab A

**Additional context**
The app does work on my desktop with no problem, but I cant use on a mobile. I think this is due to having multiple streams.

**Comment by nicolocarpignoli** [comment] 2019-10-15 12:23
duplicate of https://github.com/jeromeetienne/AR.js/issues/571, continue/ask more there

**Comment by nicolocarpignoli** [comment] 2019-10-15 12:23
thanks!

**Closed by nicolocarpignoli** 2019-10-15 12:23 UTC

**Comment by MichaelVonB** [comment] 2019-10-15 12:59
Correct me if I'm wrong but I think you missunderstood. I have a QR-Scanner in the same HTML as the ar.js app. I just dont understand how and where ar.js creates the video stream.
