### ISSUE TITLE
Playing audio on marker detect

### ISSUE THREAD

**Issue by peterlunglum** [jeromeetienne/AR.js#335] opened 2018-04-26 04:08 UTC
How would I get an event listener to work with marker detection?

I've looked around and found a fork for this in an unmerged repo, but to use the main repo, looks like I would have to registerComponent? 

I have the following added in a script tag after Aframe and AR.JS are called on, but placed before the a-scene. 

```
AFRAME.registerComponent('registerevents', {
		init: function () {
			var marker = this.el;

			// Make the element emit events when found and when lost.
			marker.setAttribute('emitevents', 'true');

			marker.addEventListener('markerFound', function() {
				var markerId = marker.id;
				console.log('markerFound', markerId);
				console.log("Marker Found!");
				// TODO: Add your own code here to react to the marker being found.
			});

			marker.addEventListener('markerLost', function() {
				var markerId = marker.id;
				console.log('markerLost', markerId);
				console.log("Marker Gone!");
				// TODO: Add your own code here to react to the marker being lost.
			});
		}
	}); 
```

Here's the scene:

```
    <a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false;';>
	  	<a-marker preset="hiro" registerevents emitevents="true">
	            <a-box position='0 0.5 0' material='color: black;'></a-box>
	  	</a-marker>
  	  	<a-assets>
    		<audio id="sound" src="audio.mp3" preload="auto"></audio>
  		</a-assets>
  	<a-entity sound="src: #sound" autoplay="false"></a-entity>
  	<a-entity camera></a-entity>
    </a-scene>
```

From registering the component though, it doesn't seem to even console.log when the marker is detected. Any ideas on why?

**Comment by donmccurdy** [comment] 2018-05-01 17:40
See https://github.com/jeromeetienne/AR.js/issues/217 and https://github.com/jeromeetienne/AR.js/pull/303. The `markerFound` event does not exist in AR.js yet — until some sort of event is made available in the AR.js library, you'll likely need to compile a custom version of the library or check visibility and emit events yourself unfortunately.

**Comment by cesarmiguel85** [comment] 2018-05-04 11:44
Hi @peterlunglum 
As explained in [this post](https://github.com/donmccurdy/aframe-extras/issues/227), you can register a component in aframe that checks if the marker is visible...

Here is the code to put in your header
`<script>
	//To avoid playing from start if the marker flickers, not sure if needed, but it might be a failsafe when you have mutiple markers and want to make sure the first finishes before launching the second
	var playing = false;
	
	//HTML5 audio, will need user touch input to start on mobile
	var intro = new Audio('sound.mp3');

	//Detect end of audio
	intro.addEventListener("ended", function() {
		intro.currentTime = 0;
		playing = false;
	});

	AFRAME.registerComponent('markerhandler', {
		init: function() {
			// Set up the tick throttling. Will check if marker is active every 500ms
			this.tick = AFRAME.utils.throttleTick(this.tick, 500, this);
		},
		tick: function(t, dt) {
			
			if (document.querySelector("#your_marker_id").object3D.visible == true && playing == false) {
				// MARKER IS PRESENT
				intro.play();
				playing = true;
			} else {
				// MARKER IS HIDDEN, do nothing (up to you)
			}

		}
	});
</script>`

And of course, add the id to your a-marker

Hope this helps :-)

**Comment by vettorazi** [comment] 2018-07-07 16:08
"adding a id in the a-marker"?
what do you mean?

**Comment by vettorazi** [comment] 2018-07-07 22:32
yeah, i get it.
i asked cuz i never saw an id inside the a-marker tag. i tried put an id in the a-marker tag, but didn't see to work.
`  if (document.querySelector("#markerid").object3D.visible == true) {`

`<a-marker-camera preset='hiro' registerevents emitevents="true" id="markerid"></a-marker-camera>`

**Comment by nicolocarpignoli** [comment] 2018-07-09 13:07
duplicate of https://github.com/jeromeetienne/AR.js/issues/335

**Comment by nicolocarpignoli** [comment] 2018-08-07 12:31
For me the 'visible' options was always false in marker, but was true for the <a-entity> element inside that marker. So I did the same thing but using an id for the a-entity marker and check for it, instead of doing the check on the marker element

**Comment by nicolocarpignoli** [comment] 2018-08-08 07:09
@vettorazi try with this properties on the element (and maybe try also a-marker instead of a-marker-camera if the first doesn't work):

`<a-marker markerhandler cursor="rayOrigin: mouse" emitevents="true" id="animated-marker" preset='hiro'></a-marker>`

**Comment by nicolocarpignoli** [comment] 2018-08-08 08:47
I collect what i learned about events on ar.js in this article. It contains a full working example for click events. Hope it helps! 

https://medium.com/chialab-open-source/how-to-handle-click-events-on-ar-js-58fcacb77c4

**Comment by nicolocarpignoli** [comment] 2018-08-31 07:53
@peterlunglum @vettorazi if this is solved / obsolete I will close, let us know please

**Comment by nicolocarpignoli** [comment] 2018-11-13 08:09
@delphinoluiz 

see this repo. on index.html you have the element definition and on events.js you have your eventListeners for click events, when a user click on the 3D object that is shown on top of the marker.

Now, if you want to play an audio track, simply call 'play()' method of HTML5 audio elements  https://www.w3schools.com/jsref/met_audio_play.asp


In the example I provide, on events.js, I do something inside the callback of click events. In that case, I change the scale of the 3D object. Instead, you could play an audio:

```
// instead of this:
  const scale = aEntity.getAttribute('scale');
  Object.keys(scale).forEach((key) => scale[key] = scale[key] + 1);
 aEntity.setAttribute('scale', scale);
```

```
// do something like this:
 const audio = document.querySelector('audio');
audio.play();
```

Of course you have to attach an `audio` element on the index.html with the `src` attribute that points to a valid audio source.

:)

**Comment by delphinoluiz** [comment] 2018-11-13 08:40
@nicolocarpignoli Thank you very much. I want to play "video" using <a-video> etc.
Can you help me? Do you have any repo for video play?

**Comment by nicolocarpignoli** [comment] 2018-11-13 09:07
@delphinoluiz never used it sorry :) you can check here 

https://aframe.io/docs/0.8.0/primitives/a-video.html

**Comment by delphinoluiz** [comment] 2018-11-13 12:40
@nicolocarpignoli Thanks

**Comment by nicolocarpignoli** [comment] 2018-11-13 13:15
you're welcome @delphinoluiz

**Closed by nicolocarpignoli** 2018-11-13 13:15 UTC

**Comment by Shabeera185** [comment] 2021-03-22 14:23
how to play audios for marker ,when you have 6 audio files for 6 respective markers in webAR using AFRAME and AR.js.

I am trying to create a web application where I want different audios to be played on detecting different markers.(Each marker has been assigned an audio file.only one marker will be shown at a time.

I had create eventlistners for all 6 files as follows

`<script>
  window.onload = function() {
    AFRAME.registerComponent("audiohandler", {
      init: function() {
        var marker = this.el;

        this.sid2 = document.querySelector("#sid2");

        marker.addEventListener(
          "markerFound",
          function() {
            this.sid2.play();
          }.bind(this)
        );

        marker.addEventListener(
          "markerLost",
          function() {
            this.sid2.pause();
            this.sid2.currentTime = 0;
          }.bind(this)
        );
      }
    });
  };
</script>
`
the audio asset was added as follows:
 `<audio
        src="https://arjs-cors-proxy.herokuapp.com/https://raw.githack.com/Shabeera185/BookAR/main/audioBEE.mp3"
        preload="auto"
        id="sid2"
        response-type="arraybuffer"
        loop
        autoplay
        
      >`

and the audio has been placed under<nft>  tag as 
`<a-audio src="#sid2"> </a-audio>`


when the programme is run, whichever audiohandler is put at last in <script> tag that is alone played.
how could I solve this problem?

**Comment by Shabeera185** [comment] 2021-03-22 14:26
`<script>
  window.onload = function() {
    AFRAME.registerComponent("audiohandler", {
      init: function() {
        var marker = this.el;

        this.sid = document.querySelector("#sid");

        marker.addEventListener(
          "markerFound",
          function() {
            this.sid.play();
          }.bind(this)
        );

        marker.addEventListener(
          "markerLost",
          function() {
            this.sid.pause();
            this.sid.currentTime = 0;
          }.bind(this)
        );
      }
    });
  };
</script>
`
