### ISSUE TITLE
WebcamError NotReadableError Could not start video source on my GalaxyS10

### ISSUE THREAD

**Issue by EugeneFitzher** [jeromeetienne/AR.js#692] opened 2020-01-02 06:42 UTC
Hello, I'm using Samsung Galaxy S10 ( G977, QP1A.190711.020 ) version Android 10 and chrome version 79.0.3945.93.

I'm new to webAR, and I'm trying to learn AR.js, but there are errors when I open the every AR websites you suggested to test or fix the following bug and every examples included on ar.js github said: 'Webcam Error Name: NotReadableError, Message: Could not start video source'.
(not present in your browser -> solved with https)
I found the way that changing camera can solve this problem some cases, but for me, just white site is showing.
( I used these links to try:
https://codepen.io/nicolocarpignoli/full/KKwzRdJ => just white sites, CHANGE CAMERA works nothing.
https://nicolo-carpignoli-herokuapp.com/select-camera => WebcamError shown first, and when I click 'Switch camera' button, chrome said on status bar: Accessing video input. Touch to return to https:// ~ .' But also white site no contents just 'Switch Camera' and VR button. )
I'm trying to solve this problem, but I can't.

How can I solve it?

Thanks.

**Comment by pidzvnese** [comment] 2020-01-05 15:26
I have the same problem, who can help me?

**Comment by nicolocarpignoli** [comment] 2020-01-06 08:56
Hi everybody

I guess the problem is the camera, as default Chrome it's picking the wrong camera as the first one.

To verify if it's that: please try any AR.js app with Mozilla Firefox and let us know, if the problems occurs again.

**Comment by nicolocarpignoli** [comment] 2020-01-06 08:58
Firefox should make you choose between all of your cameras (or at least 2+) and one of them should be the correct one to use.

**Comment by nicolocarpignoli** [comment] 2020-01-06 11:31
So for this problem, this PR is crucial now
https://github.com/jeromeetienne/AR.js/pull/661

**Comment by EugeneFitzher** [comment] 2020-01-13 00:02
@nicolocarpignoli firefox works fine. https://nicolo-carpignoli.herokuapp.com/select-camera/ 
You are right. The problem is chrome do not select the camera correctly.

**Comment by nicolocarpignoli** [comment] 2020-01-13 07:40
Yes. As a backup for now you can use Firefox. At least until someone makes/fixes that PR

**Comment by nicolocarpignoli** [comment] 2020-01-21 18:08
closing this one, there are a lot of duplicates, like: https://github.com/jeromeetienne/AR.js/issues/581

**Closed by nicolocarpignoli** 2020-01-21 18:08 UTC
Labels: bug

**Comment by Jaco-Jonker** [comment] 2020-09-23 12:52
@nicolocarpignoli - I know you closed this thread, but cannot seem to find a solution to allowing Android devices to select a camera through Chrome? I also do not have the option of using Firefox as the new Huawei devices being released does not currently have support for Firefox? Is there a solution to this yet?
