### ISSUE TITLE
Example Links not Working

### ISSUE THREAD

**Issue by Jaysonvdw** [jeromeetienne/AR.js#312] opened 2018-03-06 02:34 UTC
Hello,

These links return "Page not Found".

![image](https://user-images.githubusercontent.com/8292543/37011172-976439e6-20f7-11e8-8d47-142b6c56393f.png)

Please assist.

Thank you.

Jay

**Comment by nicolocarpignoli** [comment] 2018-07-04 15:53
duplicate of https://github.com/jeromeetienne/AR.js/issues/362

**Closed by nicolocarpignoli** 2018-07-04 15:53 UTC
Labels: documentation
