### ISSUE TITLE
Tested the Example; Doesn't work on Chrome on IOS?

### ISSUE THREAD

**Issue by farhanRIT** [jeromeetienne/AR.js#476] opened 2019-02-18 19:16 UTC
I tested the given sample;
The sample from the main page https://github.com/jeromeetienne/AR.js
The QR code or this https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html

The camera is not loaded, when testing on Chrome on IOS.
I tested on my iPhone 6 and iPhone X, works on Safari but not on Chrome browser.

Is this not supported on Chrome on IOS devices?
I get an error saying 
Webcam Error
Name:
Message: WebRTC issue-!
nagivator.mediaDevices not present in your browser.

While on Android, it works fine on chrome browser but not native  browser (has scaling issue) I tested on Samsung Galaxy S5 and Samsung Galaxy Tab. The camera feed is at a smaller scale and the object does not appear at a proper position over the mark.

**Comment by janpio** [comment] 2019-02-18 20:00
Which sample? There are many in the repository.

**Comment by farhanRIT** [comment] 2019-02-18 20:10
Sorry. I meant the sample from the main page https://github.com/jeromeetienne/AR.js
The QR code or this https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html

I get that Webcam error when trying to run on chrome on IOS as well as on Android as in my first message

**Comment by janpio** [comment] 2019-02-19 09:49
The https://github.com/jeromeetienne/AR.js#browser-support section currently is not very good.

I am alos getting an error for the mobile-performance example on current Chrome on current iOS:

![2019-02-19 10 47 28](https://user-images.githubusercontent.com/183673/53005648-f468dc00-3433-11e9-882d-603641d7a104.png)

But this is more or less expected as Chrome internally uses a WebView which on iOS doesn't support the tech needed for AR.js to work.

**Comment by nicolocarpignoli** [comment] 2019-02-20 08:53
As I told here https://github.com/jeromeetienne/AR.js/issues/463 probably you have not given access to the web page to your mic/camera.
delete caches on chrome devtools/application and reload. the same on ios

**Comment by nicolocarpignoli** [comment] 2019-02-20 08:53
also duplicates #463. answer there. thanks

**Comment by janpio** [comment] 2019-02-20 14:36
@nicolocarpignoli Well, you missed the point here. This is about Chrome on iOS. As this doesn't even prompt for permission, there is no way to not give access.

**Comment by nicolocarpignoli** [comment] 2019-02-20 14:54
sorry about that. for this purpose, I think this can be useful: https://stackoverflow.com/questions/24063238/why-does-chrome-not-show-the-prompt-with-allow-or-disallow-permission-to-microph

**Comment by nicolocarpignoli** [comment] 2019-02-20 15:02
In general, I think this kind of issues are not, in any way, related to AR.js.
AR.js uses a lot of different libraries and it is web based, so developers will found a lot of problems. This is ok, but I think AR.js issues have to remain a place for AR.js-strictly-related-bugs and proposals or similar, not somewhere where to put all problems about AR.js implementations.

I think that **the problem is absolutely not with developers** digging on AR.js but rather on this repo that do not have a clear separate place where to discuss such things - well, there is https://gitter.im/AR-js/Lobby, but it is not well known and not well structured.

Anyway, it is better to discuss this on Trello or other place :)

@farhanRIT let us know if the previous post can help you with your problem

**Comment by andreyrd** [comment] 2019-02-21 17:53
iOS does not allow `getUserMedia` in WKWebView, which all third party browsers (such as Chrome) are forced to use.
There's nothing that we or anyone can do about this. :(
It's 100% up to Apple.

Here is the relevant Open Radar: http://www.openradar.me/33571214
It's been open for almost 2 years now.

**Comment by nicolocarpignoli** [comment] 2019-02-21 19:06
Thanks @andreyrd 
I think we can close this for now. Not solvable and, more important, not a AR.js issue.

**Closed by nicolocarpignoli** 2019-02-21 19:06 UTC

**Comment by janpio** [comment] 2019-02-21 19:12
(To be honest it is, as it is not properly documented in README.md - the "Browser Support" section is terrible - which is why https://trello.com/c/3V7ITJGx/14-rework-browser-support-section exists to solve this better)

**Comment by Digilux** [comment] 2020-06-02 22:33
i have this issue on my Samsung Note 10 with Chrome.

**Comment by HerrDrFink** [comment] 2021-09-16 06:54
I had the same Issue...
**But i found a solution and it's quite easy.**

When you have this Error Message:
_"Webcam Error
Name:
Message: WebRTC issue-!
nagivator.mediaDevices not present in your browser."_

please make sure that you host your website with an **ssl-certificate**.
I installed Centos 7 on a Virtual Machine and host an apache server with an self-signed-ssl-certificate.

Then I connected again with "https://" and it works fine.

Please check this!
I hope that helps in all cases.

**Thank you** @nicolocarpignoli for sharing this amazing project!
