### ISSUE TITLE
Smartphone with multi-cameras

### ISSUE THREAD

**Issue by jamess922** [jeromeetienne/AR.js#581] opened 2019-08-30 03:47 UTC
When open a ar.js demo，is that possible to change camera when use a smartphone which has multi cameras，like huawei mate 20，we want to use the main camera ，but it's not use the main camera by default.

**Comment by cconnor12345** [comment] 2019-08-30 08:22
I've had this same issue, it uses the 3x camera on my mate 20 phone by default. I'm not sure if this would be a software bug with Huawei though

**Comment by nicolocarpignoli** [comment] 2019-08-30 10:22
There are a lot of old issues opened about that. Please check this search results:

https://github.com/jeromeetienne/AR.js/issues?utf8=%E2%9C%93&q=camera+rear

**Comment by jamess922** [comment] 2019-09-02 01:46
Like cconnor12345 said ,now the problem is huawei mate phone has 3x rear cameras ，how could we change camera

**Comment by nicolocarpignoli** [comment] 2019-09-02 07:11
it's possible to get media source streams of all devices (all cameras, mics, and so on) with https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices and similar APIs.

The problem is, we have to add a way to AR.js to dynamically change on user request the media stream used. THe default is the front camera. No way for now to change that.

This is somehow duplicate of https://github.com/jeromeetienne/AR.js/issues/571 though is different

**Comment by evaristoc** [comment] 2019-09-07 23:10
@nicolocarpignoli Are you really sure there is no way to change that? Is there no way to manipulate the `arToolkitSource` module?

**Comment by nicolocarpignoli** [comment] 2019-09-09 07:03
sorry, I was not so specific. I wanted to say there is no easy way to change that. Maybe hacking into the code will make this possible. Have to investigate tho

**Comment by cconnor12345** [comment] 2019-10-18 12:02
I have produced some code in #619 that should resolve this issue

**Comment by nicolocarpignoli** [comment] 2020-01-21 18:08
There is a PR for this. Have to find the time to work on. If someone is willing to help, i can provide support

**Closed** 2020-03-04 20:21 UTC
